# Generated by Django 5.0 on 2024-01-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('distinctive_features', models.TextField(blank=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_known_location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_item_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
